name: Terraform Deployment

on:
  workflow_run:
    workflows:
      - Build and Push to ECR
    types:
      - completed

env:
  AWS_REGION: us-east-1
  TF_DIR: terraform

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ env.TF_DIR }}
        run: terraform init -reconfigure -backend-config="environments/dev/backend.hcl"

      - name: Terraform Validate
        working-directory: ${{ env.TF_DIR }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: ${{ env.TF_DIR }}
        run: |
          IMAGE_TAG=${{ github.event.workflow_run.head_sha }}

          terraform plan \
          -var-file="environments/dev.tfvars" \
          -var="image_tag=$IMAGE_TAG" \
          -out="dev.tfplan"


      - name: Terraform Apply
        working-directory: ${{ env.TF_DIR }}
        run: terraform apply -auto-approve dev.tfplan